### ISSUE TITLE
A basic question about "testHost" parameter

### ISSUE THREAD

**Issue by cyclops24** [256cats/check-proxy#2]
Hi @256cats,
First thanks for your awesome package.
I have a basic question. `http://ping.rhcloud.com/` not accessible from my internet. What is 'testHost` actually does? Is it optional?

**Comment by 256cats** [comment]
Hi, 

Yes, it's required. It's an address of server.js. 

The library consists of server which checks incoming request parameters and a client which tries to connect through different proxies to the server (check example folder). 

You need to run them both and server.js should be accessible from the internet.

So, testHost can be, for example, http://your-website.com:8080 if you run server.js on your-website.com, port 8080

**Comment by cyclops24** [comment]
Thanks for your attention.
But I need use you module in Meteor and I want to use server and client on a same machine. Is it possible with your module?

**Comment by 256cats** [comment]
Yes, it will work fine if your machine has dedicated IP address accessible from the internet.

**Comment by cyclops24** [comment]
Thanks for your rapid reply?
What about local call? Is it possible to run app on localhost totaly without deploy to a server?

**Comment by 256cats** [comment]
No, server.js should be accessible from internet for this library to work

**Comment by cyclops24** [comment]
Thanks man.
So do you have any plan to make this independent from server.js and express for using in other framework like meteor?

**Comment by 256cats** [comment]
Not sure about that. Library doesn't depend on express. Server.js is just an example, you can use any other framework with it.

**Comment by cyclops24** [comment]
@256cats Thanks man. So I can try using this in Meteor and ask my questions.
I close this issue. :wink:
