### ISSUE TITLE
can not install, after yarn add check-proxy

### ISSUE THREAD

**Issue by xPomaHx** [256cats/check-proxy#7]
`roman@bro-dev:/home/admin/web/nodeProject/proxycheckerserver$ yarn add check-proxy
yarn add v1.6.0
(node:3634) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
warning check-proxy > geoip-ultralight > rimraf > graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning check-proxy > geoip-ultralight > unzip > fstream > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⡀ node-libcurl:                                           ^
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
error /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.4.1 | linux | x64
node-pre-gyp info check checked for "/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v64-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and node@10.4.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v64-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
node-pre-gyp ERR! Tried to download(undefined): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and node@10.4.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/roman/.node-gyp/10.4.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/roman/.node-gyp/10.4.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/roman/.node-gyp/10.4.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/roman/.node-gyp/10.4.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@10.4.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: вход в каталог «/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build»
make: вход в каталог «/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build»
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/node_libcurl.cc:25:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from ../../nan/nan.h:190:0,
                 from ../src/node_libcurl.cc:25:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:833:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:833:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:848:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:863:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1477:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:848:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:863:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1477:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_libcurl.cc:24:0:
/home/roman/.node-gyp/10.4.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/roman/.node-gyp/10.4.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
node_libcurl.target.mk:105: ошибка выполнения рецепта для цели «Release/obj.target/node_libcurl/src/node_libcurl.o»
make: выход из каталога «/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build»
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Ошибка 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/usr/bin/node" "/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.4.0-128-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl
node-pre-gyp ERR! node -v v10.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding' (1)
node_libcurl.target.mk:105: ошибка выполнения рецепта для цели «Release/obj.target/node_libcurl/src/node_libcurl.o»
make: выход из каталога «/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/build»
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Ошибка 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/usr/bin/node" "/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /home/admin/web/nodeProject/proxycheckerserver/node_modules/node-libcurl

roman@bro-dev:/home/admin/web/nodeProject/proxycheckerserver$ `

**Comment by xPomaHx** [comment]
this problem with node-libcurl, it not work on node v.10

**Comment by 256cats** [comment]
Libcurl dependency was removed
