### ISSUE TITLE
Issue with libcurl dependency

### ISSUE THREAD

**Issue by mattxgreen** [256cats/check-proxy#8]
I believe the release version on npm is older (out of sync) with this version on github. Dependency list when installed via npm shows: 

```
"dependencies": {
    "bluebird": ">=3.1.1",
    "geoip-ultralight": "0.1.5",
    "lodash": "4.17.4",
    "node-libcurl": "git+https://github.com/256cats/node-libcurl.git#develop",
    "tslib": "1.7.1"
  }
```
VS:
```
  "dependencies": {
    "bluebird": ">=3.1.1",
    "geoip-ultralight": "0.1.5",
    "lodash": "4.17.4",
    "tslib": "1.7.1",
    "node-libcurl": "1.3.0"
  },
```

You can see libcurl is being pulled from a git repo, which requires git to be installed on the host. An update on npm would be appreciated. Thanks.

**Comment by 256cats** [comment]
Libcurl dependency was removed.
